huskey added

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,9 +5,9 @@ npm run format ||
     true;
 )
 
-npm run lint ||
+npm run check-types ||
 (
-    echo '🤡❌🤡 Failed Linting. 🤡❌🤡 Are you seriously trying to write that? Make the changes required above.'
+    echo '🤡❌🤡 Failed Type Check. 🤡❌🤡 Are you seriously trying to write that? Make the changes required above.'
     false;
 )
 
